name: Release JavaScript Package

on: workflow_call

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
