name: Release JavaScript Package

on:
  workflow_call:
    secrets:
      npmToken:
        required: true
      gitHubToken:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.gitHubToken }}
          NPM_TOKEN: ${{ secrets.npmToken }}
        run: yarn run semantic-release
